before_install:
  - gem update --system
  - gem install bundler
before_script:
  - psql -c 'create database blocitoff_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test
rvm:
  - {{ cookiecutter.ruby_version }}
sudo: false